name: "Upload to S3rei"
description: "Uploads a file to AWS S3"
author: "Surya"
branding:
  icon: "upload-cloud"
  color: "blue"

inputs:
  file:
    description: "Path to the file to upload"
    required: true
  bucket:
    description: "S3 bucket name"
    required: true
  aws-region:
    description: "AWS region where bucket exists"
    required: true
  aws-access-key-id:
    description: "AWS Access Key ID"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Upload file to S3
      shell: bash
      run: aws s3 cp "${{ inputs.file }}" "s3://${{ inputs.bucket }}/"
