name: "Upload to S3"
description: "Uploads a file to AWS S3"
inputs:
  file:
    required: true
  bucket:
    required: true
  aws-region:
    required: true
runs:
  using: "composite"
  steps:
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws-region }}

    - name: Upload file
      shell: bash
      run: aws s3 cp "${{ inputs.file }}" "s3://${{ inputs.bucket }}/"
